### ISSUE TITLE
Incorrect instanceRoot in gulp-config.js

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/Sitecore.HabitatHome.Content#17]
The README states that the default URL for the site is `https://habitathome.dev.local`, so I'd expect the webroot to be `C:\inetpub\wwwroot\habitathome.dev.local` but the `gulp-config.js` has `C:\inetpub\wwwroot\habitat.dev.local` set as the `instanceRoot`. This should be changed to `C:\inetpub\wwwroot\habitathome.dev.local`.

**Comment by jeanfrancoislarente** [comment]
Done.
