### ISSUE TITLE
habitat-logo Causes Errors on Site Publish

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/Sitecore.HabitatHome.Content#18]
Whenever I do a full, smart site publish, I get the following exception:

> Job started: Publish to 'web'|#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more exceptions occurred while processing the subscribers to the 'item:adding' event.
>    at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)
>    at Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)
>    at Sitecore.Events.Event.RaiseItemCreating(Object sender, ItemCreatingEventArgs args)
>    at Sitecore.Events.Event.DataEngine_CreatingItem(Object sender, ExecutingEventArgs`1 e)
>    at Sitecore.Data.Engines.EngineCommand`2.RaiseEvent[TArgs](EventHandler`1 handlers, Func`2 argsCreator)
>    at Sitecore.Data.Engines.EngineCommand`2.RaiseExecuting(Boolean& cancelled)
>    at Sitecore.Data.Engines.EngineCommand`2.CanExecute()
>    at Sitecore.Data.Engines.EngineCommand`2.Execute()
>    at Sitecore.Data.Engines.DataEngine.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created)
>    at Sitecore.Data.Managers.ItemProvider.DoCreateAndReturnItem(String itemName, Item destination, ID templateId, ID newId, DateTime created)
>    at Sitecore.Data.Managers.ItemProvider.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created, SecurityCheck securityCheck)
>    at Sitecore.Data.Managers.DefaultItemManager.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created, SecurityCheck securityCheck)
>    at Sitecore.Data.Managers.ItemManager.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created, SecurityCheck securityCheck)
>    at Sitecore.Publishing.PublishHelper.CreateTargetItem(Item sourceVersion)
>    at Sitecore.Publishing.PublishHelper.PublishVersion(Item sourceVersion)
>    at Sitecore.Publishing.Pipelines.PublishItem.PerformAction.Process(PublishItemContext context)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Publishing.Pipelines.PublishItem.PublishItemPipeline.Run(PublishItemContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context, List`1& referrers, List`1& children)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.Process(PublishContext context)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Publishing.Pipelines.Publish.PublishPipeline.Run(PublishContext context)
>    at Sitecore.Publishing.Publisher.PublishWithResult()
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
>    at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Jobs.Job.DoExecute()
>    at Sitecore.Jobs.Job.ThreadEntry(Object state)

This is what I see in the log:

> 21144 21:40:43 ERROR One or more exceptions occurred while processing the subscribers to the 'item:adding' event.
> Exception[1]: System.NullReferenceException 
> Message[1]: Object reference not set to an instance of an object. 
> Source[1]: Sitecore.Kernel 
>    at Sitecore.Web.UI.Sheer.ClientPage..ctor(HttpContextBase httpContext)
>    at Sitecore.Context.get_ClientPage()
>    at Sitecore.XA.Foundation.Multisite.EventHandlers.VirtualMediaFolderValidator.CancelEvent(SitecoreEventArgs evt)
>    at Sitecore.XA.Foundation.Multisite.EventHandlers.VirtualMediaFolderValidator.OnItemAdding(Object obj, EventArgs args)
>    at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) 
> 
> 
> 21144 21:40:43 ERROR Exception
> Exception: System.Reflection.TargetInvocationException
> Message: Exception has been thrown by the target of an invocation.
> Source: mscorlib
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
>    at Sitecore.Jobs.JobRunner.RunMethod(JobArgs args)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Jobs.Job.DoExecute()
>    at Sitecore.Jobs.Job.ThreadEntry(Object state)
> 
> Nested Exception
> 
> Exception: System.AggregateException
> Message: One or more exceptions occurred while processing the subscribers to the 'item:adding' event.
> Source: Sitecore.Kernel
>    at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)
>    at Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)
>    at Sitecore.Events.Event.RaiseItemCreating(Object sender, ItemCreatingEventArgs args)
>    at Sitecore.Events.Event.DataEngine_CreatingItem(Object sender, ExecutingEventArgs`1 e)
>    at Sitecore.Data.Engines.EngineCommand`2.RaiseEvent[TArgs](EventHandler`1 handlers, Func`2 argsCreator)
>    at Sitecore.Data.Engines.EngineCommand`2.RaiseExecuting(Boolean& cancelled)
>    at Sitecore.Data.Engines.EngineCommand`2.CanExecute()
>    at Sitecore.Data.Engines.EngineCommand`2.Execute()
>    at Sitecore.Data.Engines.DataEngine.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created)
>    at Sitecore.Data.Managers.ItemProvider.DoCreateAndReturnItem(String itemName, Item destination, ID templateId, ID newId, DateTime created)
>    at Sitecore.Data.Managers.ItemProvider.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created, SecurityCheck securityCheck)
>    at Sitecore.Data.Managers.DefaultItemManager.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created, SecurityCheck securityCheck)
>    at Sitecore.Data.Managers.ItemManager.CreateItem(String itemName, Item destination, ID templateId, ID newId, DateTime created, SecurityCheck securityCheck)
>    at Sitecore.Publishing.PublishHelper.CreateTargetItem(Item sourceVersion)
>    at Sitecore.Publishing.PublishHelper.PublishVersion(Item sourceVersion)
>    at Sitecore.Publishing.Pipelines.PublishItem.PerformAction.Process(PublishItemContext context)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Publishing.Pipelines.PublishItem.PublishItemPipeline.Run(PublishItemContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context, List`1& referrers, List`1& children)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessPublishingCandidate(PublishingCandidate entry, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.ProcessEntries(IEnumerable`1 entries, PublishContext context)
>    at Sitecore.Publishing.Pipelines.Publish.ProcessQueue.Process(PublishContext context)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
>    at Sitecore.Publishing.Pipelines.Publish.PublishPipeline.Run(PublishContext context)
>    at Sitecore.Publishing.Publisher.PublishWithResult()
> 
> 
> 22032 21:40:43 INFO  Job ended: Publish (units processed: )

I've tested the following scenarios:
- Smart item publish of `/sitecore/content/Habitat Sites/Habitat`
  - ❌ With subitems
  - ❌ With related items
  - ❌ With subitems and related items
- Smart item publish of `/sitecore/content/Habitat Sites/Habitat Home`
  - ✔️ With subitems
  - ❌ With related items
  - ❌ With subitems and related items

Further digging under `/sitecore/content/Habitat Sites/Habitat` I've found that a single item publish of `/sitecore/content/Habitat Sites/Habitat/Media/habitat-logo` always throws the error above. There may be other items causing the issue as well, but I haven't looked further.

**Comment by jeanfrancoislarente** [comment]
Has anyone else encountered this issue?

**Comment by jeanfrancoislarente** [comment]
Thanks @viethoangpyco

**Comment by sitecoremaster** [comment]
I am also getting this issue.  With the latest version.  I was able to disable publish on that logo and then smart publish the site and everything worked fine.  I think there's something wrong with the logo.

**Comment by jeanfrancoislarente** [comment]
Hey @sitecoremaster - are you on 9.0.1.9? Just making sure we're tracking the right one.

We're in the middle of the upgrade/update to 9.0.2. We'll make sure it works there.

**Comment by ezlateva** [comment]
Hey guys, I ran into this too! The habitat-logo media item is sitting right under the tenant's media folder, which isn't something SXA allows - there's an event handler that runs and validates that nothing is sitting directly under. The workaround is to move the logo media item to a media library folder. Publish worked for me after that

@jeanfrancoislarente Looks like this is already resolved in the 9.0.2 branch

**Comment by jeanfrancoislarente** [comment]
Thanks @ezlateva  - missed the fact that it was fixed in 9.0.2

I'll leave the workaround as the solution for current version since I'll be merging 9.0.2 into master/develop as early as next week.
