### ISSUE TITLE
Add GDPR complaint functionality to demo

### ISSUE THREAD

**Issue by chorpo** [Sitecore/Sitecore.HabitatHome.Content#27]
As a visitor of Habitat Home, I would like to have new Privacy page, where I could export data which "Habitat" knows about me like personal information + all interactions (following Right to be access data from GDPR). I would also like to see there possibility to erase / anonymize my account (following Right to be forgotten from GDPR).

**Comment by jeanfrancoislarente** [comment]
Thanks @chorpo! 

Feel free to post questions / approach and I'll try to get some validation when/where possible.

**Comment by chorpo** [comment]
I will try to do pull request next week. I almost have code prepared

**Comment by chorpo** [comment]
Implemented by #57 . More PR will come in the future to make some enhancements. For now closing.
