### ISSUE TITLE
Sitecore xConnect Search Indexer Windows Service cannot be started

### ISSUE THREAD

**Issue by chorpo** [Sitecore/Sitecore.HabitatHome.Content#45]
**Describe the bug**
Sitecore xConnect Search Indexer Windows Service cannot be started

**To Reproduce**
1. Go to 'Windows Services'
2. Try to start 'Sitecore xConnect Search Indexer - instance_name - IndexWorker' Windows Service
3. Service cannot be started with error and with exceptions logged:

> [Error] Detected an unexpeted error while the indexer was running.
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Unable to resolve service for type 'Sitecore.Xdb.Collection.Indexing.IIndexInitializer' while attempting to activate 'Sitecore.Xdb.Collection.Indexing.SingleThreadedIndexer'.
>    at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
>    at Microsoft.Extensions.Configuration.ConfigurationServiceType.<>c__DisplayClass24_0.<op_Implicit>b__0(IServiceProvider sp)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Sitecore.XConnect.Search.Indexer.IndexerHost..ctor(IConfigurationRoot config)
>    at Sitecore.XConnect.Search.Indexer.IndexerAppDomainHost.IndexerHostAppDomainBridge..ctor()
>    --- End of inner exception stack trace ---
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(String assemblyName, String typeName)
>    at System.AppDomain.CreateInstance(String assemblyName, String typeName)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName)
>    at Sitecore.XConnect.Search.Indexer.IndexerAppDomainHost.CreateAppDomainAndIndexer()
>    at Sitecore.XConnect.Search.Indexer.IndexerAppDomainHost.IndexerHostAppDomainRestarter(TaskCompletionSource`1 indexerExitCompletionSource)

**Expected behavior**
Sitecore xConnect Search Indexer Windows Service can be started without any issues

**Comment by jeanfrancoislarente** [comment]
@chorpo can you provide more details?
Were you able to reproduce this on a "clean" instance of XP?
Was it working before?

**Comment by chorpo** [comment]
This has been already fixed in latest commits by somebody else
